version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: papertrading-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: papertrading
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
