spring.application.name=app-backend
mailjet.api-key=81f7316fbd5d3fe6a1b824ddd3ff9e2b
mailjet.secret-key=5af26b5e7f9e57bc345983a32607e6d4
mailjet.from-email=saivarunreddy31@gmail.com
mailjet.from-name=Trix


